<?xml version="1.0" ?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="roscontrol">

  <xacro:property name="wheeldiam" value="0.4" />
  <!-- <xacro:property name="pi" value="3.141" /> -->

  <link name="base_footprint"/>

  <link name="base_link">
    <inertial>
      <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
      <mass value="1.0"/>
      <inertia ixx="0.4" ixy="0.0" ixz="0.0"
               iyy="0.4" iyz="0.0"
               izz="0.2"/>
    </inertial>
    <visual name="">
      <origin xyz="0.0 0.0 1.0" rpy="0.0 0.0 0.0"/>
      <geometry>
        <box size="0.8 0.8 0.4"/>
      </geometry>
      <material name="black">
        <color rgba="0.0 0.0 0.0 1.0"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
      <geometry>
        <box size="0.8 0.8 0.4"/>
      </geometry>
    </collision>
  </link>

  <joint name="base_joint" type="fixed">
    <origin xyz="0.0 0.0 0.135" rpy="0.0 0.0 0.0"/>
    <parent link="base_footprint"/>
    <child link="base_link"/>
    <axis xyz="0.0 0.0 0.0"/>
  </joint>

  <xacro:macro name="wheel" params="prefix suffix x y wheeldiam">
    <link name="${prefix}_${suffix}_wheel">
      <inertial>
        <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
        <mass value="0.5"/>
        <inertia ixx="0.0" ixy="0.0" ixz="0.0" iyy="0.0" iyz="0.0" izz="0.0"/>
      </inertial>
      <visual name="">
        <origin xyz="0.0 0.0 0.0" rpy="${pi/2} 0.0 0.0"/>
        <geometry>
          <cylinder radius="${wheeldiam/2.0}" length="0.2"/>
        </geometry>
        <material name="black">
          <color rgba="0.0 0.0 0.0 1.0"/>
        </material>
      </visual>
      <collision>
        <origin xyz="0.0 0.0 0.0" rpy="${pi/2} 0.0 0.0"/>
        <geometry>
          <cylinder radius="${wheeldiam/2.0}" length="0.1"/>
        </geometry>
      </collision>
    </link>

    <joint name="${prefix}_${suffix}_wheel_joint" type="continuous">
      <origin xyz="${x} ${y} 0" rpy="0 0.0 0.0"/>
      <parent link="base_link"/>
      <child link="${prefix}_${suffix}_wheel"/>
      <axis xyz="0.0 0.0 1.0"/>
    </joint>
  </xacro:macro>

  <!-- Wheel Creating using macros -->
  <xacro:wheel prefix="rear_right" suffix="" x="0.2" y="0.455" />
  <xacro:wheel prefix="front_right" suffix="" x="-0.2" y="0.455"/>
  <xacro:wheel prefix="front_left" suffix="" x="-0.2" y="-0.455" />
  <xacro:wheel prefix="rear_left" suffix="" x="0.2" y="-0.455" />


  
</robot>
